### ISSUE TITLE
github-notifier hangs

### ISSUE THREAD

**Issue by oceatoon** [abiczo/github-notifier#18]
hi 
I've jsut installed the notifier on Ubuntu  14.04
and executed it , untill there it's all good 
but it just hangs 
should it be launched in background ?

**Comment by abiczo** [comment]
Hey, yeah the script doesn't background itself so what you're seeing is
expected behavior. You can background it manually (e.g. by using &).

Adding a flag that runs the script in the background would also be nice. I
won't have time to work on this but would be happy to merge a pull request.

Let me know if this answers your question or if i misunderstood you.

**Comment by abiczo** [comment]
Let me know if I misunderstood your question and we can reopen this issue.

**Comment by dotnetCarpenter** [comment]
@abiczo Would be nice if `github-notifier` would output some kind of confirmation text, that it is running without any issues.

**Comment by abiczo** [comment]
@dotnetCarpenter that's a good idea. Unfortunately I don't have a linux machine at the moment so it'd be hard for me to make any changes but if you'd be interested sending out a pull request I'd be happy to merge it.
